---
title: "APPLY FAMILY"
output: html_document
---


```{r}

student <-  read.csv("file:///D:/DATA SCIENCE/DATASET/Student_data.csv")
student


summary(student)
#APPLY FAMILY 
#apply(data frame,1 for row and 2 for column,function to apply)
#we are taking min value of every row and binding it into an data frame 
student1 <- cbind(student,apply(student, 1,min))
student2 <- cbind(student,apply(student, 1,max))
student3 <- cbind(student,apply(student, 1,mean))
student6 <- cbind(student,apply(student[,], 1,cat))
student5 <- cbind(student,apply(student,1,sum))

#to change particulat column name 
colnames(student5)[4] <- c("TOTAL")



```


```{r}
#LAPPLY FUNCTION (IT RETURN LIST)
CAGO <- data.frame(Dite1=c(4,2,5,7,8,3,5,1,3,6),Dite2=c(3,6,8,3,2,7,5,4,8,9),Dite3=c(9,3,2,4,6,8,7,4,3,1),Dite4=c(2,3,1,5,6,8,4,5,6,3))

class(lapply(CAGO,mean)) #lapply(dataframe,function) it return value in list

#sapply (return value in simplified)
c <- sapply(CAGO,mean) # IT apply the function on column bydefault ...... it reurn numeric vector
#Binding the the in the orignal data frame.
CAGO <- rbind(CAGO,c)

```



